set nocompatible              " be iMproved, required
filetype off                  " required

let mapleader = ","
syntax on
set number
set noswapfile
set hlsearch
set ignorecase
set incsearch

inoremap { {}<Esc>ha
inoremap ( ()<Esc>ha
inoremap [ []<Esc>ha
inoremap " ""<Esc>ha
inoremap ' ''<Esc>ha
inoremap ` ``<Esc>ha
