### PATH
export PATH=$PATH:$HOME/go/bin
export ZSH="$HOME/.zsh"

source "$ZSH/init.sh"

### Plugins and scripts 
plugins=(
    dirhistory
    fancy-ctrl-z
    git
    sudo
    tmux
    zsh-syntax-highlighting
    zsh-autosuggestions
)

# Load all of the plugins that were defined in ~/.zshrc
for plugin ($plugins); do
if [[ -f "$ZSH/plugins/$plugin/$plugin.plugin.zsh" ]]; then
    source "$ZSH/plugins/$plugin/$plugin.plugin.zsh"
fi
done
unset plugin

# Load config files
for config_file ("$ZSH"/lib/*.zsh); do
  source "$config_file"
done

### Theming
ZSH_THEME="cobalt2"
source "$HOME/.zsh/themes/$ZSH_THEME.zsh-theme"

### TMUX Config
export KUBE_TMUX_CLUSTER_FUNCTION=get_cluster_short
export ZSH_TMUX_AUTOSTART=true

### Editor
if [[ -n $SSH_CONNECTION ]]; then
  export EDITOR='vim'
else
  export EDITOR='nvim'
fi

### Aliases
source $HOME/.aliases
#source $HOME/.aliases.work

[[ $commands[kubectl] ]] && source <(kubectl completion zsh)

ulimit -n 10240
