#!/bin/zsh

swaylock -f \
    --image ~/Pictures/Wallpapers/wallpaper.png \
    --clock \
    --font "JetBrains Mono Nerd Font" \
    --indicator \
    --indicator-radius 100 \
    --indicator-thickness 7 \
    --effect-blur 7x5 \
    --effect-vignette 0.5:0.5 \
    --grace 2 \
    --fade-in 0.2
